"""The Week 5 traffic. Written before anything was run, with no expected answers.

117 desk questions and 10 demo questions. The desk set is what a claims desk would
actually type at this endorsement pack: half of it names a form or a code, half of it
describes a loss and expects the assistant to find the form. Some of it is barely a
question at all, because a busy adjuster types "water exclusions please" and moves on.

Nothing here records what a correct answer would be. A question set with answers
attached is a benchmark, and a benchmark written by the person who already knows
where the app is weak measures the author, not the app. These are questions only.

Claimant names, claim numbers, policy numbers, phones and addresses appear in the
desk set on purpose. Real file notes carry them, and a redactor that has never been
handed one has not been tested.
"""

DESK_SET = [
 ("D001", "Water came in under the patio door in heavy rain. Which exclusion code covers that?"),
 ("D002", "Rebecca Hollis, claim CLM-2024-88431. Burst supply line under HO-0304 ed. 03-24. Does E-17 knock it out?"),
 ("D003", "What is the seepage trigger period for E-17 on the 09-23 edition of HO-0304?"),
 ("D004", "Under HO-0304 ed. 01-25, does the E-17 burst supply line exception still apply if no shut-off device was installed?"),
 ("D005", "Insured left the house vacant over winter and a pipe froze. Heat was kept on. Excluded?"),
 ("D006", "What is the Limited Water Damage Sublimit on HO-0304?"),
 ("D007", "Water damage deductible per occurrence under the limited water damage endorsement?"),
 ("D008", "Is there an annual aggregate on HO-0304 water damage?"),
 ("D009", "water damage exclusions please"),
 ("D010", "Does HO-0304 pay to replace the failed section of pipe itself?"),
 ("D011", "How long does the insured have to report a water loss under HO-0304?"),
 ("D012", "Policy HO-99213, insured dried the property nine days after discovery. Any mitigation issue?"),
 ("D013", "Plumber's inspection report is dated eight months before the loss. Does the deductible change?"),
 ("D014", "Two paid water claims in 30 months. Can we non-renew?"),
 ("D015", "Mould grew after a covered burst pipe. Is there any cover, and is it capped?"),
 ("D016", "Sewer backup into the basement. Which code, and is there a buy-back?"),
 ("D017", "Hot tub filtration unit leaked and damaged the deck. Covered under HO-0304?"),
 ("D018", "Groundwater seeping through the basement wall. Which exclusion?"),
 ("D019", "E-14 versus E-15, what is the actual difference?"),
 ("D020", "Does E-17 on HO-0304 apply to the plumbing system itself or only to other property?"),
 ("D021", "Insured says the leak started suddenly but was found five weeks later. Which way does that go?"),
 ("D022", "Is a drain line a supply line for the purposes of these endorsements?"),
 ("D023", "Define sudden and accidental as we apply it to the seepage exception."),
 ("D024", "A slow drip that later burst open. Sudden and accidental or not?"),
 ("D025", "Where does the seepage period start running from, the leak or the discovery?"),
 ("D026", "House under renovation, utilities on, nobody living there. Is that vacant?"),
 ("D027", "What is the difference between vacant and unoccupied in our wording?"),
 ("D028", "Empty 22 days, pipe burst, heat was on. Do we pay?"),
 ("D029", "Mr Alvarez, policy HO-88104. Rental dwelling on DP-3, pipe burst in the kitchen. Which form applies?"),
 ("D030", "Does DP-0431 apply to a homeowners risk?"),
 ("D031", "What is the water damage buy-back sublimit on the dwelling fire form?"),
 ("D032", "Water damage deductible on DP-0431?"),
 ("D033", "DP-0431 ed. 04-24 E-17 - is there any sudden and accidental exception on the dwelling fire form?"),
 ("D034", "Seepage trigger on the dwelling fire endorsement, how many days?"),
 ("D035", "Rental sat empty 40 days and a line let go. DP-0431, any way home?"),
 ("D036", "Does the E-21 vacancy exclusion on DP-0431 have an exception?"),
 ("D037", "Supply line was manufactured in 2011, failed last month. DP-0431. Excluded?"),
 ("D038", "Reporting deadline on the DP-0431 buy-back?"),
 ("D039", "Two bathroom rental renewed in November 2024, no shut-off device fitted. Where does that leave the buy-back?"),
 ("D040", "Client asks why the dwelling fire wording is harsher than the homeowners one on seepage."),
 ("D041", "Asphalt shingle roof, 12 years old, hail loss. What percentage of replacement cost do we pay?"),
 ("D042", "Metal roof, 18 years old, windstorm. What is the ACV factor?"),
 ("D043", "Slate roof at 27 years. Anything payable?"),
 ("D044", "Roof is 32 years old. Hail loss. Position?"),
 ("D045", "Insured says hail knocked granules off the shingles but the roof is not leaking. Covered, or cosmetic?"),
 ("D046", "Hail dented the metal roof but it still sheds water and there are no leaks. Does the cosmetic exclusion apply?"),
 ("D047", "Is there a buy-back for the cosmetic damage exclusion on HO-0455?"),
 ("D048", "What does E-22 exclude on endorsement HO-0455 ed. 01-24?"),
 ("D049", "Roofer re-flashed a valley six weeks before the storm. Does that matter?"),
 ("D050", "Same facts, but the roofer was licensed in state. Does the exclusion still bite?"),
 ("D051", "No documentation of roof age anywhere in the file. What age do we assume?"),
 ("D052", "Water got in through the storm-damaged roof and ruined the ceiling. Is the ceiling on ACV too?"),
 ("D053", "How is roof age measured, from manufacture or from installation?"),
 ("D054", "Is the deductible taken before or after the ACV factor?"),
 ("D055", "Ordinance or law limit after HO-0612, what percentage of Coverage A?"),
 ("D056", "How much ordinance or law coverage does the increased-amount endorsement provide?"),
 ("D057", "After the ordinance or law increase endorsement, what is the cap on increased cost of construction?"),
 ("D058", "Does the increased ordinance or law amount erode the Coverage A limit?"),
 ("D059", "Does HO-0612 cover demolition of the undamaged part of the house?"),
 ("D060", "City requires the whole electrical panel brought to code as a permit condition. Covered?"),
 ("D061", "Asbestos found in the ceiling we have to open up. Any cover for abatement?"),
 ("D062", "What is the sublimit on asbestos abatement under HO-0612?"),
 ("D063", "The house was already in violation of the setback ordinance before the fire. Do we pay to fix that?"),
 ("D064", "Insured wants the diminished value of the property after the code upgrade. Payable?"),
 ("D065", "Uncovered flood loss triggers a code upgrade requirement. Do we pay the upgrade?"),
 ("D066", "Policy is rated HO-3. Does HO-0612 apply?"),
 ("D067", "Do we pay to upgrade beyond the minimum the code requires if the contractor recommends it?"),
 ("D068", "What documentation do we need before paying an ordinance or law claim?"),
 ("D069", "Policyholder runs a bookkeeping business from a spare bedroom, no staff, no clients on site, about $8k a year. Does the business exclusion knock out the claim?"),
 ("D070", "What makes something a business under our definitions - is there a dollar threshold?"),
 ("D071", "Is there a buy-back for E-32 under HO-2199 ed. 02-24?"),
 ("D072", "Guest booked through a short-term rental platform started a kitchen fire. Excluded?"),
 ("D073", "Laptop went missing the morning after the short-term guest checked out. Covered?"),
 ("D074", "Does the home-sharing exclusion reach the 24 hours after the guest leaves?"),
 ("D075", "Insured never told us about the short-term letting. What are our options?"),
 ("D076", "Furniture bought specifically for the rental guests was damaged. Covered?"),
 ("D077", "Guest slipped on the stairs and is claiming against the insured. Liability position?"),
 ("D078", "Insured let the place out 70 nights this year. Eligibility?"),
 ("D079", "What is the home-sharing surcharge?"),
 ("D080", "Makes candles at home, cleared about 8,000 dollars last year. A customer tripped in the driveway. Are we on cover for the liability?"),
 ("D081", "Storage of goods for sale in the garage. Business exclusion or not?"),
 ("D082", "Which policy line is HO-0612 written for?"),
 ("D083", "Which policy line is DP-0431 written for?"),
 ("D084", "Does HO-0788 apply to endorsements or only to the base wording?"),
 ("D085", "If HO-0788 and HO-0304 define a term differently, which one wins?"),
 ("D086", "Can HO-0788 create coverage that HO-0304 excludes?"),
 ("D087", "Escape started suddenly, insured could not reasonably have known, found after 40 days. Seepage exclusion or the definitions clause?"),
 ("D088", "Ms Okafor, claim CLM 2025 10422, reached on 555-201-8890. Water under the laminate, unclear when it started. How do we approach it?"),
 ("D089", "Does the seepage definition require the leak to be continuous, or does recurring count?"),
 ("D090", "Homeowners policy, burst pipe in a rental unit the insured owns elsewhere. Which form applies?"),
 ("D091", "Both HO-0304 and DP-0431 are in the file. Which one governs?"),
 ("D092", "Does E-17 mean the same thing on HO-0304 and on DP-0431?"),
 ("D093", "Two different editions of HO-0304 are in the file. How do I tell which one is on risk?"),
 ("D094", "E-21 appears on both HO-0455 and DP-0431. Are they the same exclusion?"),
 ("D095", "E-22 on HO-0455 versus E-22 on DP-0431 - what is the difference?"),
 ("D096", "Does failing to fit the shut-off device void the whole claim or just the buy-back?"),
 ("D097", "Does failing to notify us of home-sharing void the whole policy or just that loss?"),
 ("D098", "Insured already had the roof replaced before we got out there. Where does that leave us?"),
 ("D099", "What is our subrogation deadline against the plumber?"),
 ("D100", "What is the reserve-setting threshold for a water loss of this size?"),
 ("D101", "Who is the assigned adjuster for policy HO-99213, and what is their direct phone number?"),
 ("D102", "What is the current reinsurance attachment point for our homeowners book this treaty year?"),
 ("D103", "Is there any appraisal clause in these endorsements?"),
 ("D104", "Does any of our wording set a time limit for the insured to file suit?"),
 ("D105", "Do these endorsements say anything about depreciation holdback release?"),
 ("D106", "Loss is 14,000 dollars, HO-0304 is attached and the sublimit applies. What do we pay?"),
 ("D107", "Two separate water losses four days apart. One deductible or two?"),
 ("D108", "Does the water damage deductible apply per occurrence or per claim?"),
 ("D109", "Tear-out to reach the failed pipe - is that inside or outside the sublimit?"),
 ("D110", "Does the $2,000 system repair payment sit inside the sublimit?"),
 ("D111", "Sprinkler head let go in a vacant unit. Which exclusion do I read first?"),
 ("D112", "Pool pump failed and flooded the equipment room. Position under HO-0304?"),
 ("D113", "Insured says the escape was sudden but the neighbour reported hearing running water for a fortnight. How does that read?"),
 ("D114", "Ordinance work needed on the plumbing after a covered fire, HO-5 policy. Covered under HO-0612?"),
 ("D115", "Short-term guest damaged the rented furniture and stole a television. Two exclusions or one?"),
 ("D116", "Does the cosmetic damage exclusion on HO-0455 reach interior water damage?"),
 ("D117", "Roof work done 100 days before the loss by an unlicensed contractor. Does E-24 apply?"),
]

# The ten we bring to the monthly review. Same pipeline, separate trace file.
DEMO_SET = [
 ("M01", "What is the Limited Water Damage Sublimit on HO-0304?"),
 ("M02", "What is the water damage deductible per occurrence under HO-0304?"),
 ("M03", "After the ordinance or law increase endorsement, what is the cap on increased cost of construction?"),
 ("M04", "What percentage of Coverage A is the ordinance or law limit under HO-0612?"),
 ("M05", "Asphalt shingle roof, 11 to 15 years old. What percentage do we pay?"),
 ("M06", "What does E-22 exclude on HO-0455 ed. 01-24?"),
 ("M07", "Is there a buy-back for E-32 under HO-2199 ed. 02-24?"),
 ("M08", "What is the home-sharing surcharge under HO-2199?"),
 ("M09", "What is the water damage buy-back sublimit under DP-0431 ed. 04-24?"),
 ("M10", "What is the increased cost of construction cap in the base wording, before HO-0612?"),
]

assert len(DESK_SET) == 117, len(DESK_SET)
assert len(DEMO_SET) == 10, len(DEMO_SET)
assert len({q for q, _ in DESK_SET}) == 117
assert len({t for _, t in DESK_SET}) == 117, "duplicate question text"
